### ISSUE TITLE
Add page for packages

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/nhs-r-community#219]
Although we don't have hex stickers for all the packages a page bringing everything together could be a good start and prompt for artistic contributions 😄

**Comment by anyaferguson** [comment]
Hi @Lextuga007. I’m looking into this, but could you please tell me where I can find the hexes we have?

Was thinking for each package we would have the description from their repo, the hex (if applicable) and links to the repo and CRAN (if applicable). Also a general note on how contributions are welcome. Was there anything else you thought would be good to add?

**Comment by Lextuga007** [comment]
We don't have hex stickers for books just yet 😃 I was thinking something like this https://psyteachr.github.io/ from the University of Glasgow (so they use inspiration from Rennie Mackintosh. For packages, some have them, some don't.

**Comment by anyaferguson** [comment]
I am still looking at this. I've created some very basic hexes we can use as placeholders for now like this:
![NHSRpostcodetoolslogo](https://github.com/user-attachments/assets/249f213e-08ee-44dc-9ee9-c06a85b50534).

I've also had a go at designing a couple:
![nhsrdatasetslogo](https://github.com/user-attachments/assets/e25b8965-a9f7-4a2a-959d-558a31c320b8)

![nhsrepisodeslogo](https://github.com/user-attachments/assets/a1348d26-49d4-4a9c-8b74-ac200d18127e)

![nhsrthemelogo](https://github.com/user-attachments/assets/1318cbec-736c-48be-923b-a0beca8bb4f6)

All using code similar to the NHSRplotthedots hex, so using [hexSticker](https://github.com/GuangchuangYu/hexSticker/tree/master and using colours from NHSRtheme. Happy to use them, scrap them or take feedback and tweak them, but am not sure on the process for getting these approved? If we want to use them, I'll share the code in their corresponding repos.

**Comment by anyaferguson** [comment]
Sorry, if you got a whole bunch of notifications. I was trying to figure out how to resize the images and failed.

**Comment by Lextuga007** [comment]
Not a problem! I only got notifications from the comment issues and 😍 those hexes!

**Comment by anyaferguson** [comment]
Would it be ok to put the NHSRdatasets, NHSRtheme, NHSRepisodes and NHSplotthedots hexes on the hexSticker repo? https://github.com/GuangchuangYu/hexSticker/tree/master

**Comment by Lextuga007** [comment]
Absolutely!

**Comment by anyaferguson** [comment]
PR to add the 4 hexes to the hexSticker readme gallery: https://github.com/GuangchuangYu/hexSticker/pull/182
