### ISSUE TITLE
Peer review for this UI/UX

### ISSUE THREAD

**Issue by Vacansa** [nhs-r-community/nhs-r-community#224]
### Discussed in https://github.com/nhs-r-community/nhs-r-community/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **Vacansa** October 18, 2024</sup>
Considering downloading this element for a client in England. 

https://demos.webicode.com/html/medikal/?storefront=envato-elements</div>

**Comment by nnaemek2** [comment]
Right move! Do it.
