### ISSUE TITLE
Link to RSS

### ISSUE THREAD

**Issue by anyaferguson** [nhs-r-community/nhs-r-community#231]
On the home page at the bottom in the supporters section, clicking on the RSS logo takes me to https://www.theorsociety.com/. Should it be https://rss.org.uk/ instead?

**Comment by Lextuga007** [comment]
Oh I tried to fix that but forgot to accept the PR! Thanks for the issue 😄

**Comment by Lextuga007** [comment]
@all-contributors please add @anyaferguson for bug
