### ISSUE TITLE
Dark mode is broken

### ISSUE THREAD

**Issue by StatsRhian** [nhs-r-community/nhs-r-community#242]
Background is set to white when in dark-mode. 
This is causing contrast issues.

<img width="900" alt="dark-mode" src="https://github.com/user-attachments/assets/ee6190f2-1039-4f1a-bd60-febbb2106000">

Potentially came in via https://github.com/nhs-r-community/nhs-r-community/pull/238

**Comment by Lextuga007** [comment]
@all-contributors please add @StatsRhian for bug
