### ISSUE TITLE
No link to the slack on the about page alongside the other channels?

### ISSUE THREAD

**Issue by helenajr** [nhs-r-community/nhs-r-community#268]
![image](https://github.com/user-attachments/assets/e00ba3a0-56e3-4a0a-9f40-4fba3a940071)

Can't find a link to the slack anywhere on the website? Maybe it should go on the about page alongside the other social media channels, or in the getting involved section?

**Comment by Lextuga007** [comment]
Great question! The Slack link runs out periodically and I was also cautious of putting it on the website as it's the most public area we have. We've already had a bit of spam on the GitHub (funnily enough it was quite technical so it was issues and discussions which was surprising!). 

Saying that, it would be a good idea to still put something about Slack and a link to where the access link 
is: https://postcard.nhsrcommunity.com/ so I've put this as an enhancement. I'm more than happy for you to have a go at adding this as a PR and I can talk you through it if you'd like.

**Comment by helenajr** [comment]
No worries, didn't realise the link runs out. I'll have a go at adding the link to the postcard.
