### ISSUE TITLE
Adding tab for ways to get involved

### ISSUE THREAD

**Issue by anyaferguson** [nhs-r-community/nhs-r-community#45]
It may be good to add a 'getting involved', 'contribute' or 'how you can help' tab / page to the website so if people want to help out they can easily find all the information they need. For example, this could include links to the github issues page with advice on how to work on an issue, or links to sign up to offer training.

**Comment by Lextuga007** [comment]
@anyaferguson ideas

**Comment by Lextuga007** [comment]
Trying again now I've added the section in the README 😁 

@all-contributors
please add @anyaferguson for ideas

**Comment by Lextuga007** [comment]
Trying again as I caused a merge conflict in my hasty adding of two contributors 😁 

@all-contributors
please add @anyaferguson for ideas
